#!/usr/bin/env python3
"""
Script to add remaining sections (5-10) to the Kalenjin ASR preprocessing pipeline notebook.
"""

import json
from pathlib import Path

def add_sections_to_notebook():
    """Add sections 5-10 to the notebook."""
    
    notebook_path = Path("notebooks/kalenjin_asr_preprocessing_pipeline.ipynb")
    
    # Read existing notebook
    with open(notebook_path, 'r') as f:
        notebook = json.load(f)
    
    # New sections to add
    new_cells = [
        # Section 5: Quality Assessment Module
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "---\n",
                "## 5. Quality Assessment Module <a id='section5'></a>\n",
                "\n",
                "### Comprehensive Quality Framework\n",
                "\n",
                "The quality assessment module implements multi-dimensional evaluation:\n",
                "- **Audio Quality**: SNR, spectral analysis, clipping detection\n",
                "- **Text Quality**: Linguistic validity, character analysis\n",
                "- **Alignment Quality**: Audio-text correspondence metrics\n",
                "- **Statistical Analysis**: Outlier detection and quality distributions"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Import quality assessment module\n",
                "import sys\n",
                "sys.path.append('../scripts')\n",
                "from quality_assessment import AudioQualityAssessor, TextQualityAssessor, QualityThresholds\n",
                "\n",
                "# Initialize quality assessors\n",
                "quality_thresholds = QualityThresholds()\n",
                "audio_assessor = AudioQualityAssessor(quality_thresholds)\n",
                "text_assessor = TextQualityAssessor(quality_thresholds)\n",
                "\n",
                "print('✓ Quality assessment module loaded')\n",
                "print('✓ Audio and text quality assessors initialized')"
            ]
        },
        
        # Section 6: Dataset Structuring Module
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "---\n",
                "## 6. Dataset Structuring Module <a id='section6'></a>\n",
                "\n",
                "### Dataset Organization Strategy\n",
                "\n",
                "Optimal dataset structuring for ASR training requires:\n",
                "- **Stratified Sampling**: Balanced representation across speakers/domains\n",
                "- **Duration Distribution**: Optimal length distribution for training\n",
                "- **Train/Validation/Test Splits**: Proper data leakage prevention\n",
                "- **Metadata Management**: Comprehensive sample annotations"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "class DatasetStructurer:\n",
                "    \"\"\"Advanced dataset structuring for ASR training.\"\"\"\n",
                "    \n",
                "    def __init__(self, config: ProcessingConfig):\n",
                "        self.config = config\n",
                "        self.metadata = {}\n",
                "        \n",
                "    def create_splits(self, data: List[Dict], test_size: float = 0.2, val_size: float = 0.1) -> Dict[str, List]:\n",
                "        \"\"\"Create stratified train/validation/test splits.\"\"\"\n",
                "        # First split: train+val vs test\n",
                "        train_val, test = train_test_split(\n",
                "            data, \n",
                "            test_size=test_size, \n",
                "            random_state=self.config.random_seed\n",
                "        )\n",
                "        \n",
                "        # Second split: train vs val\n",
                "        train, val = train_test_split(\n",
                "            train_val, \n",
                "            test_size=val_size/(1-test_size), \n",
                "            random_state=self.config.random_seed\n",
                "        )\n",
                "        \n",
                "        return {\n",
                "            'train': train,\n",
                "            'validation': val,\n",
                "            'test': test\n",
                "        }\n",
                "    \n",
                "    def create_huggingface_dataset(self, splits: Dict[str, List]) -> DatasetDict:\n",
                "        \"\"\"Create HuggingFace Dataset format.\"\"\"\n",
                "        dataset_dict = {}\n",
                "        \n",
                "        for split_name, split_data in splits.items():\n",
                "            # Prepare data for HuggingFace format\n",
                "            hf_data = {\n",
                "                'audio': [item['audio'] for item in split_data],\n",
                "                'text': [item['normalized_text'] for item in split_data],\n",
                "                'duration': [item['duration'] for item in split_data]\n",
                "            }\n",
                "            \n",
                "            dataset_dict[split_name] = Dataset.from_dict(hf_data)\n",
                "            dataset_dict[split_name] = dataset_dict[split_name].cast_column('audio', Audio(sampling_rate=16000))\n",
                "        \n",
                "        return DatasetDict(dataset_dict)\n",
                "\n",
                "print('✓ DatasetStructurer class defined')"
            ]
        },
        
        # Section 7: Pipeline Orchestration
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "---\n",
                "## 7. Pipeline Orchestration <a id='section7'></a>\n",
                "\n",
                "### Modular Pipeline Architecture\n",
                "\n",
                "The orchestration system coordinates all preprocessing modules:\n",
                "- **Parallel Processing**: Multi-core audio/text processing\n",
                "- **Memory Management**: Efficient batch processing\n",
                "- **Error Handling**: Robust failure recovery\n",
                "- **Progress Tracking**: Comprehensive logging and monitoring"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "class PreprocessingPipeline:\n",
                "    \"\"\"Master preprocessing pipeline orchestrator.\"\"\"\n",
                "    \n",
                "    def __init__(self, config: PreprocessingConfig):\n",
                "        self.config = config\n",
                "        self.audio_processor = AudioProcessor(config.audio)\n",
                "        self.text_normalizer = TextNormalizer(config.text)\n",
                "        self.dataset_structurer = DatasetStructurer(config.processing)\n",
                "        self.results = []\n",
                "        \n",
                "    def process_sample(self, audio_path: str, text: str) -> Optional[Dict]:\n",
                "        \"\"\"Process a single audio-text pair.\"\"\"\n",
                "        try:\n",
                "            # Process audio\n",
                "            audio_result = self.audio_processor.process_audio_file(audio_path)\n",
                "            if not audio_result or not audio_result['is_valid']:\n",
                "                return None\n",
                "            \n",
                "            # Process text\n",
                "            text_result = self.text_normalizer.normalize_text(text)\n",
                "            if not text_result['is_valid']:\n",
                "                return None\n",
                "            \n",
                "            # Combine results\n",
                "            return {\n",
                "                'audio_path': audio_path,\n",
                "                'audio': audio_result['audio'],\n",
                "                'sample_rate': audio_result['sample_rate'],\n",
                "                'duration': audio_result['duration'],\n",
                "                'original_text': text,\n",
                "                'normalized_text': text_result['normalized'],\n",
                "                'audio_metrics': {k: v for k, v in audio_result.items() if k not in ['audio', 'file_path']},\n",
                "                'text_metrics': text_result['metrics']\n",
                "            }\n",
                "            \n",
                "        except Exception as e:\n",
                "            logger.error(f\"Error processing sample {audio_path}: {e}\")\n",
                "            return None\n",
                "    \n",
                "    def run_pipeline(self, data_pairs: List[Tuple[str, str]]) -> Dict[str, Any]:\n",
                "        \"\"\"Run complete preprocessing pipeline.\"\"\"\n",
                "        logger.info(f\"Starting pipeline with {len(data_pairs)} samples\")\n",
                "        \n",
                "        # Process samples in parallel\n",
                "        with ProcessPoolExecutor(max_workers=self.config.processing.n_jobs) as executor:\n",
                "            results = list(tqdm(\n",
                "                executor.map(lambda x: self.process_sample(x[0], x[1]), data_pairs),\n",
                "                total=len(data_pairs),\n",
                "                desc=\"Processing samples\"\n",
                "            ))\n",
                "        \n",
                "        # Filter valid results\n",
                "        valid_results = [r for r in results if r is not None]\n",
                "        \n",
                "        logger.info(f\"Pipeline completed: {len(valid_results)}/{len(data_pairs)} samples valid\")\n",
                "        \n",
                "        return {\n",
                "            'processed_data': valid_results,\n",
                "            'total_samples': len(data_pairs),\n",
                "            'valid_samples': len(valid_results),\n",
                "            'success_rate': len(valid_results) / len(data_pairs) if data_pairs else 0\n",
                "        }\n",
                "\n",
                "print('✓ PreprocessingPipeline class defined')"
            ]
        },
        
        # Section 8: Validation & Quality Control
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "---\n",
                "## 8. Validation & Quality Control <a id='section8'></a>\n",
                "\n",
                "### Multi-Level Validation Framework\n",
                "\n",
                "Comprehensive validation ensures data quality:\n",
                "- **Statistical Validation**: Distribution analysis and outlier detection\n",
                "- **Linguistic Validation**: Text quality and consistency checks\n",
                "- **Audio Validation**: Signal quality and technical specifications\n",
                "- **Cross-Validation**: Audio-text alignment verification"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "class QualityValidator:\n",
                "    \"\"\"Comprehensive quality validation system.\"\"\"\n",
                "    \n",
                "    def __init__(self, config: PreprocessingConfig):\n",
                "        self.config = config\n",
                "        \n",
                "    def validate_dataset_statistics(self, data: List[Dict]) -> Dict[str, Any]:\n",
                "        \"\"\"Validate dataset statistical properties.\"\"\"\n",
                "        durations = [item['duration'] for item in data]\n",
                "        word_counts = [item['text_metrics']['word_count'] for item in data]\n",
                "        \n",
                "        stats = {\n",
                "            'duration_stats': {\n",
                "                'mean': np.mean(durations),\n",
                "                'std': np.std(durations),\n",
                "                'min': np.min(durations),\n",
                "                'max': np.max(durations),\n",
                "                'total_hours': np.sum(durations) / 3600\n",
                "            },\n",
                "            'text_stats': {\n",
                "                'mean_words': np.mean(word_counts),\n",
                "                'std_words': np.std(word_counts),\n",
                "                'total_words': np.sum(word_counts)\n",
                "            }\n",
                "        }\n",
                "        \n",
                "        return stats\n",
                "    \n",
                "    def detect_outliers(self, data: List[Dict]) -> List[int]:\n",
                "        \"\"\"Detect statistical outliers in the dataset.\"\"\"\n",
                "        durations = np.array([item['duration'] for item in data])\n",
                "        \n",
                "        # Use IQR method for outlier detection\n",
                "        Q1 = np.percentile(durations, 25)\n",
                "        Q3 = np.percentile(durations, 75)\n",
                "        IQR = Q3 - Q1\n",
                "        \n",
                "        lower_bound = Q1 - 1.5 * IQR\n",
                "        upper_bound = Q3 + 1.5 * IQR\n",
                "        \n",
                "        outlier_indices = np.where((durations < lower_bound) | (durations > upper_bound))[0]\n",
                "        \n",
                "        return outlier_indices.tolist()\n",
                "\n",
                "print('✓ QualityValidator class defined')"
            ]
        },
        
        # Section 9: Export & Model Preparation
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "---\n",
                "## 9. Export & Model Preparation <a id='section9'></a>\n",
                "\n",
                "### Multi-Format Export System\n",
                "\n",
                "The export module supports multiple ASR frameworks:\n",
                "- **HuggingFace Datasets**: Direct integration with Transformers\n",
                "- **JSON Format**: Flexible metadata preservation\n",
                "- **CSV Format**: Tabular data analysis\n",
                "- **Model-Specific**: Optimized formats for different architectures"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "class DataExporter:\n",
                "    \"\"\"Multi-format data export system.\"\"\"\n",
                "    \n",
                "    def __init__(self, config: ProcessingConfig):\n",
                "        self.config = config\n",
                "        \n",
                "    def export_huggingface(self, dataset: DatasetDict, output_dir: Path) -> None:\n",
                "        \"\"\"Export to HuggingFace Dataset format.\"\"\"\n",
                "        output_dir.mkdir(parents=True, exist_ok=True)\n",
                "        dataset.save_to_disk(str(output_dir / 'huggingface_dataset'))\n",
                "        logger.info(f\"HuggingFace dataset saved to {output_dir / 'huggingface_dataset'}\")\n",
                "    \n",
                "    def export_json(self, data: List[Dict], output_path: Path) -> None:\n",
                "        \"\"\"Export to JSON format.\"\"\"\n",
                "        output_path.parent.mkdir(parents=True, exist_ok=True)\n",
                "        with open(output_path, 'w', encoding='utf-8') as f:\n",
                "            json.dump(data, f, ensure_ascii=False, indent=2)\n",
                "        logger.info(f\"JSON data saved to {output_path}\")\n",
                "    \n",
                "    def export_csv(self, data: List[Dict], output_path: Path) -> None:\n",
                "        \"\"\"Export to CSV format.\"\"\"\n",
                "        # Flatten nested dictionaries for CSV\n",
                "        flattened_data = []\n",
                "        for item in data:\n",
                "            flat_item = {\n",
                "                'audio_path': item['audio_path'],\n",
                "                'duration': item['duration'],\n",
                "                'original_text': item['original_text'],\n",
                "                'normalized_text': item['normalized_text']\n",
                "            }\n",
                "            # Add metrics\n",
                "            for key, value in item['audio_metrics'].items():\n",
                "                flat_item[f'audio_{key}'] = value\n",
                "            for key, value in item['text_metrics'].items():\n",
                "                flat_item[f'text_{key}'] = value\n",
                "            flattened_data.append(flat_item)\n",
                "        \n",
                "        df = pd.DataFrame(flattened_data)\n",
                "        output_path.parent.mkdir(parents=True, exist_ok=True)\n",
                "        df.to_csv(output_path, index=False)\n",
                "        logger.info(f\"CSV data saved to {output_path}\")\n",
                "\n",
                "print('✓ DataExporter class defined')"
            ]
        },
        
        # Section 10: Performance Analysis
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "---\n",
                "## 10. Performance Analysis <a id='section10'></a>\n",
                "\n",
                "### Comprehensive Performance Metrics\n",
                "\n",
                "The performance analysis module provides:\n",
                "- **Processing Statistics**: Throughput and efficiency metrics\n",
                "- **Quality Distributions**: Statistical analysis of data quality\n",
                "- **Visualization**: Interactive plots and reports\n",
                "- **Benchmarking**: Performance comparison across configurations"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "class PerformanceAnalyzer:\n",
                "    \"\"\"Comprehensive performance analysis and visualization.\"\"\"\n",
                "    \n",
                "    def __init__(self):\n",
                "        self.metrics = {}\n",
                "        \n",
                "    def analyze_processing_performance(self, results: Dict[str, Any]) -> Dict[str, Any]:\n",
                "        \"\"\"Analyze preprocessing performance metrics.\"\"\"\n",
                "        data = results['processed_data']\n",
                "        \n",
                "        # Duration analysis\n",
                "        durations = [item['duration'] for item in data]\n",
                "        total_audio_hours = sum(durations) / 3600\n",
                "        \n",
                "        # Quality metrics\n",
                "        snr_values = [item['audio_metrics']['snr_db'] for item in data]\n",
                "        word_counts = [item['text_metrics']['word_count'] for item in data]\n",
                "        \n",
                "        analysis = {\n",
                "            'dataset_summary': {\n",
                "                'total_samples': len(data),\n",
                "                'total_audio_hours': total_audio_hours,\n",
                "                'success_rate': results['success_rate'],\n",
                "                'avg_duration': np.mean(durations),\n",
                "                'avg_snr': np.mean(snr_values),\n",
                "                'avg_words_per_sample': np.mean(word_counts)\n",
                "            },\n",
                "            'quality_distribution': {\n",
                "                'duration_percentiles': {\n",
                "                    'p10': np.percentile(durations, 10),\n",
                "                    'p25': np.percentile(durations, 25),\n",
                "                    'p50': np.percentile(durations, 50),\n",
                "                    'p75': np.percentile(durations, 75),\n",
                "                    'p90': np.percentile(durations, 90)\n",
                "                },\n",
                "                'snr_percentiles': {\n",
                "                    'p10': np.percentile(snr_values, 10),\n",
                "                    'p25': np.percentile(snr_values, 25),\n",
                "                    'p50': np.percentile(snr_values, 50),\n",
                "                    'p75': np.percentile(snr_values, 75),\n",
                "                    'p90': np.percentile(snr_values, 90)\n",
                "                }\n",
                "            }\n",
                "        }\n",
                "        \n",
                "        return analysis\n",
                "    \n",
                "    def create_quality_visualizations(self, data: List[Dict]) -> None:\n",
                "        \"\"\"Create comprehensive quality visualization plots.\"\"\"\n",
                "        # Extract metrics\n",
                "        durations = [item['duration'] for item in data]\n",
                "        snr_values = [item['audio_metrics']['snr_db'] for item in data]\n",
                "        word_counts = [item['text_metrics']['word_count'] for item in data]\n",
                "        \n",
                "        # Create subplots\n",
                "        fig, axes = plt.subplots(2, 2, figsize=(15, 10))\n",
                "        fig.suptitle('Kalenjin ASR Dataset Quality Analysis', fontsize=16)\n",
                "        \n",
                "        # Duration distribution\n",
                "        axes[0, 0].hist(durations, bins=50, alpha=0.7, color='skyblue')\n",
                "        axes[0, 0].set_title('Audio Duration Distribution')\n",
                "        axes[0, 0].set_xlabel('Duration (seconds)')\n",
                "        axes[0, 0].set_ylabel('Frequency')\n",
                "        \n",
                "        # SNR distribution\n",
                "        axes[0, 1].hist(snr_values, bins=50, alpha=0.7, color='lightgreen')\n",
                "        axes[0, 1].set_title('Signal-to-Noise Ratio Distribution')\n",
                "        axes[0, 1].set_xlabel('SNR (dB)')\n",
                "        axes[0, 1].set_ylabel('Frequency')\n",
                "        \n",
                "        # Word count distribution\n",
                "        axes[1, 0].hist(word_counts, bins=30, alpha=0.7, color='salmon')\n",
                "        axes[1, 0].set_title('Word Count Distribution')\n",
                "        axes[1, 0].set_xlabel('Words per Sample')\n",
                "        axes[1, 0].set_ylabel('Frequency')\n",
                "        \n",
                "        # Duration vs SNR scatter\n",
                "        axes[1, 1].scatter(durations, snr_values, alpha=0.6, color='purple')\n",
                "        axes[1, 1].set_title('Duration vs SNR Relationship')\n",
                "        axes[1, 1].set_xlabel('Duration (seconds)')\n",
                "        axes[1, 1].set_ylabel('SNR (dB)')\n",
                "        \n",
                "        plt.tight_layout()\n",
                "        plt.show()\n",
                "    \n",
                "    def generate_report(self, analysis: Dict[str, Any], output_path: Path) -> None:\n",
                "        \"\"\"Generate comprehensive analysis report.\"\"\"\n",
                "        report = f\"\"\"\n",
                "KALENJIN ASR PREPROCESSING PERFORMANCE REPORT\n",
                "{'='*50}\n",
                "\n",
                "DATASET SUMMARY\n",
                "{'-'*20}\n",
                "Total Samples: {analysis['dataset_summary']['total_samples']:,}\n",
                "Total Audio Hours: {analysis['dataset_summary']['total_audio_hours']:.2f}\n",
                "Success Rate: {analysis['dataset_summary']['success_rate']:.1%}\n",
                "Average Duration: {analysis['dataset_summary']['avg_duration']:.2f}s\n",
                "Average SNR: {analysis['dataset_summary']['avg_snr']:.1f}dB\n",
                "Average Words/Sample: {analysis['dataset_summary']['avg_words_per_sample']:.1f}\n",
                "\n",
                "QUALITY DISTRIBUTION\n",
                "{'-'*20}\n",
                "Duration Percentiles (seconds):\n",
                "  P10: {analysis['quality_distribution']['duration_percentiles']['p10']:.2f}\n",
                "  P25: {analysis['quality_distribution']['duration_percentiles']['p25']:.2f}\n",
                "  P50: {analysis['quality_distribution']['duration_percentiles']['p50']:.2f}\n",
                "  P75: {analysis['quality_distribution']['duration_percentiles']['p75']:.2f}\n",
                "  P90: {analysis['quality_distribution']['duration_percentiles']['p90']:.2f}\n",
                "\n",
                "SNR Percentiles (dB):\n",
                "  P10: {analysis['quality_distribution']['snr_percentiles']['p10']:.1f}\n",
                "  P25: {analysis['quality_distribution']['snr_percentiles']['p25']:.1f}\n",
                "  P50: {analysis['quality_distribution']['snr_percentiles']['p50']:.1f}\n",
                "  P75: {analysis['quality_distribution']['snr_percentiles']['p75']:.1f}\n",
                "  P90: {analysis['quality_distribution']['snr_percentiles']['p90']:.1f}\n",
                "\"\"\"\n",
                "        \n",
                "        output_path.parent.mkdir(parents=True, exist_ok=True)\n",
                "        with open(output_path, 'w') as f:\n",
                "            f.write(report)\n",
                "        \n",
                "        logger.info(f\"Performance report saved to {output_path}\")\n",
                "\n",
                "print('✓ PerformanceAnalyzer class defined')\n",
                "print('✓ All preprocessing modules loaded successfully')\n",
                "print('✓ Kalenjin ASR preprocessing pipeline ready for execution')"
            ]
        }
    ]
    
    # Add new cells to notebook
    notebook['cells'].extend(new_cells)
    
    # Write updated notebook
    with open(notebook_path, 'w') as f:
        json.dump(notebook, f, indent=1)
    
    print(f"✓ Added sections 5-10 to {notebook_path}")
    print("✓ Notebook now includes all preprocessing modules")

if __name__ == "__main__":
    add_sections_to_notebook()